"""Render FRR configs and docker-compose.yml from inventory/topology.yml."""

from __future__ import annotations

from pathlib import Path

import ipaddress

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = Path(__file__).resolve().parents[1]
FRR_IMAGE = "quay.io/frrouting/frr:10.1.1"


def load_topology() -> dict:
    return yaml.safe_load((ROOT / "inventory/topology.yml").read_text())


def link_view(topo: dict) -> list[dict]:
    """Flatten links into per-router rows: which subnet each router sits on, and whether it is internal (OSPF)."""
    rows = []
    for link in topo["links"]:
        internal = link["name"].startswith("l")
        for side in ("a", "b"):
            router, ip = link[side]
            rows.append(
                {
                    "router": router,
                    "link": link["name"],
                    "subnet": link["subnet"],
                    "ip": ip,
                    "internal": internal,
                    "cost": link.get("cost"),
                }
            )
    return rows


def render_frr(topo: dict, out_dir: Path = ROOT / "configs") -> list[Path]:
    env = Environment(
        loader=FileSystemLoader(ROOT / "templates"),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    tpl = env.get_template("frr.conf.j2")
    links = link_view(topo)
    written = []
    for name, r in topo["routers"].items():
        cfg = tpl.render(
            name=name,
            r={"ebgp": None, **r},
            routers=topo["routers"],
            links=links,
            asn=topo["asn"],
            aggregate=topo["aggregate"],
            preferred_isp=topo["preferred_isp"],
        )
        d = out_dir / name
        d.mkdir(parents=True, exist_ok=True)
        (d / "frr.conf").write_text(cfg)
        (d / "daemons").write_text(
            'zebra=yes\nospfd=yes\nbgpd=yes\nstaticd=yes\nvtysh_enable=yes\nzebra_options="  -A 127.0.0.1 -s 90000000"\nbgpd_options="   -A 127.0.0.1"\nospfd_options="  -A 127.0.0.1"\nstaticd_options="-A 127.0.0.1"\n'
        )
        (d / "vtysh.conf").write_text("service integrated-vtysh-config\n")
        costs = [
            f"{row['ip']} {row['cost']}"
            for row in links
            if row["router"] == name and row["internal"] and row["cost"]
        ]
        (d / "ospf-costs").write_text("\n".join(costs) + ("\n" if costs else ""))
        written.append(d / "frr.conf")
    return written


def render_compose(topo: dict, out: Path = ROOT / "docker-compose.yml") -> Path:
    services, networks = {}, {}
    for link in topo["links"]:
        # Docker gives the bridge itself an address in every subnet (default: the first host). Pin it to the last
        # usable address so router addressing stays conventional (.1, .2).
        net = ipaddress.ip_network(link["subnet"])
        networks[link["name"]] = {
            "driver": "bridge",
            "ipam": {"config": [{"subnet": link["subnet"], "gateway": str(net[-2])}]},
        }
    for name in topo["routers"]:
        nets = {
            row["link"]: {"ipv4_address": row["ip"]}
            for row in link_view(topo)
            if row["router"] == name
        }
        services[name] = {
            "image": FRR_IMAGE,
            "container_name": name,
            "hostname": name,
            "privileged": True,
            "volumes": [
                f"./configs/{name}:/etc/frr",
                "./scripts/entrypoint.sh:/entrypoint.sh:ro",
            ],
            "entrypoint": ["/bin/sh", "/entrypoint.sh"],
            "networks": nets,
            "sysctls": {
                "net.ipv4.ip_forward": 1,
                "net.ipv4.conf.all.rp_filter": 0,
                "net.ipv4.conf.default.rp_filter": 0,
            },
        }
    header = "# GENERATED by scripts/render.py from inventory/topology.yml - edit the inventory, not this file.\n"
    out.write_text(
        header
        + yaml.safe_dump({"services": services, "networks": networks}, sort_keys=False)
    )
    return out


if __name__ == "__main__":
    topo = load_topology()
    for p in render_frr(topo):
        print("wrote", p.relative_to(ROOT))
    print("wrote", render_compose(topo).relative_to(ROOT))
